FROM grafana/k6:2.2.0-with-browser

USER root

RUN apk add --no-cache \
  chromium-swiftshader \
  ca-certificates \
  nodejs \
  npm

WORKDIR /app

COPY ./ ./

# Install Node.js dependencies.
RUN npm ci --loglevel verbose

RUN npm run generate:uows

ENV CHROME_BIN=/usr/bin/chromium-browser

ENV CHROME_PATH=/usr/lib/chromium/

ENV K6_BROWSER_HEADLESS=true
# no-sandbox chrome arg is required to run chrome browser in
# alpine and avoids the usage of SYS_ADMIN Docker capability
ENV K6_BROWSER_ARGS=no-sandbox
