FROM node:18.17.1-alpine

USER node

COPY --chown=node:node . .

RUN npm ci --loglevel error --no-fund

RUN npm run build

COPY --chown=node:node /apps/user-setup/build ./apps/user-setup/build

COPY --chown=node:node /apps/k6-tests/test ./apps/k6-tests/test