apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: ${K6_TEST_FILE}-deployment
  labels:
    app: ${K6_TEST_NAME}
spec:
  parallelism: ${K6_TEST_PARALLELISM}
  script:
    configMap:
      name: test-scripts
      file: ${K6_TEST_FILE}.js
  separate: true
  arguments: --out xk6-output-opensearch --no-usage-report -e ENVIRONMENT=develop
  runner:
    image: "harbor.stfc.ac.uk/isisbusapps/uop-performance-tests-k6:${K6_VERSION_TAG}"
    imagePullPolicy: Always
    imagePullSecrets:
      - name: registry-creds
    metadata:
      annotations:
        co.elastic.logs/enabled: 'true'
        co.elastic.logs/processors.add_fields.target: ""
        co.elastic.logs/processors.add_fields.fields.application.name: "proposal-load-tester"
        co.elastic.logs/processors.add_fields.fields.application.domain: "proposal-load-testing"
        co.elastic.logs/processors.add_fields.fields.application.tier: "service"
        co.elastic.logs/processors.dissect.tokenizer: "%{?log_message}"
        co.elastic.logs/processors.dissect.ignore_failure: "true"
        co.elastic.logs/processors.dissect.target_prefix: ""
    resources:
      requests:
        cpu: "20000m"
        memory: "10Gi"
    env:
      - name: BROWSER_BASE_URL
        value: ${BROWSER_BASE_URL}
      - name: GRAPHQL_URL
        value: ${GRAPHQL_URL}
      - name: TEST_SETUP_URL
        value: ${TEST_SETUP_URL}   
      - name: K6_PS_VUS 
        value: '${K6_PS_VUS}'
      - name: K6_PS_ITERATIONS 
        value: '${K6_PS_ITERATIONS}'
      - name: SETUP_TOTAL_USERS 
        value: '${K6_SETUP_TOTAL_USERS}' 
      - name: TEST_SETUP_CALL_ID 
        value: '${TEST_SETUP_CALL_ID}'
      - name: K6_TEST_PARALLELISM
        value: '${K6_TEST_PARALLELISM}'
      - name: SETUP_TEST_USERS
        value: '${SETUP_TEST_USERS}'
      - name: SETUP_TEST_CALL
        value: '${SETUP_TEST_CALL}'
      - name: K6_OPENSEARCH_ADDRESS
        value: '${K6_OPENSEARCH_ADDRESS}'
      - name: K6_TEST_ID
        value: '${K6_TEST_ID}'
      - name: K6_OPENSEARCH_FLUSH_PERIOD
        value: '${K6_OPENSEARCH_FLUSH_PERIOD}'
      - name: IS_CLUSTER_TEST_RUN
        value: '${IS_CLUSTER_TEST_RUN}'
      - name: INSTRUMENT_ID
        value: '${INSTRUMENT_ID}'
    envFrom:
     - secretRef:
         name: connection-secrets
    volumeMounts:
      - name: features
        mountPath: "/features"
        readOnly: true
    volumes:
        - name: features
          configMap:
            name: test-features