name: Lint

on:
  push

env:
  NODE_VERSION: 20.x
  GO_VERSION: '1.22.2'
  GOLANGCI_LINT_VERSION: v1.63.4

jobs:
  run-node-linters:
    name: Run Node linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node.js dependencies
        run: npm ci

      - name: Lint Action
        run: npm run lint

  run-go-linters:
    name: Run Go linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint xk6-output-logger
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: extensions/xk6-output-logger